<?php
$fields_array['RunnableReport'] = array (
	'column_fields' => array(
		'id',
		'date_entered',
		'date_modified',
		'modified_user_id',
		'created_by',
		'name',
		'team_id',
		'assigned_user_id',
		'description',
		'settings',
		'report_result_type',
		'nextrun',
		'schedule_interval',
		'active',
		'log',
		'deleted',
	),
    'list_fields' =>  array(
		'id',
		'date_entered',
		'date_modified',
		'modified_user_id',
		'created_by',
		'name',
		'team_id',
		'assigned_user_id',
		'description',
		'settings',
		'report_result_type',
		'nextrun',
		'schedule_interval',
		'schedule_interval_desc',
		'active',
		'log',
		'deleted',
	),
    'required_fields' =>  array('name'=>1),
);
?>
